### ISSUE TITLE
`React.PropTypes.instanceOf(Prismic.Api)` warns about invalid prop

### ISSUE THREAD

**Issue by sergekovbasyuk** [prismicio/reactjs-starter#1]
I got an error message in console: 

> warning.js?8a56:36Warning: Failed prop type: Invalid prop `api` of type `Object` supplied to `DocumentListContainer`, expected instance of `getApi`.

My DocumentList.js looks the same as the original:

> DocumentListContainer.propTypes = {
  **api: React.PropTypes.instanceOf(Prismic.Api),**
  endpoint: React.PropTypes.string.isRequired,
  accesstoken: React.PropTypes.string,
  linkResolver: React.PropTypes.func.isRequired,
  q: React.PropTypes.string // Prismic query
};

What is wrong with this?

**Comment by erwan** [comment]
I started to write typings for prismic but since it's incomplete it's not committed yet. You should just replace it by "Object" (I'll fix the template too).

**Comment by sergekovbasyuk** [comment]
thanks!
